name: OfficialSite
favicon: null
layout_spectrum: 0.7847416903823614
typography_spectrum: 0.8041724632494152
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3775670153554529
  lightness: 0.6907337647862732
  saturation: 0.7783462030347437
  rhythmicContrast: 0.5803698883391917
purpose: []
